# Generated by Django 4.0.5 on 2022-06-06 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентфикатор')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего                                     обновления элемента')),
                ('parent_id', models.UUIDField(null=True, verbose_name='UUID родительской категории')),
                ('type', models.SmallIntegerField(choices=[(0, 'OFFER'), (1, 'CATEGORY')], verbose_name='Тип элемента - категория или товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
