# Generated by Django 4.0.5 on 2022-06-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopunit',
            options={'verbose_name': 'Shop Unit', 'verbose_name_plural': 'Shop Unit`s'},
        ),
        migrations.RemoveField(
            model_name='shopunit',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='shopunit',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop_unit.shopunit', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='shopunit',
            name='price',
            field=models.IntegerField(help_text='Целое число, для категории - это средняя цена                                    всех дочерних товаров(включая товары подкатегорий).                                         Если цена является не целым числом, округляется                                             в меньшую сторону до целого числа. Если категория                                                не содержит товаров цена равна null.', null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='shopunit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления элемента'),
        ),
    ]
