# Generated by Django 4.0.5 on 2022-06-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_unit', '0002_alter_shopunit_options_remove_shopunit_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop_unit.shopunit', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='shopunit',
            name='price',
            field=models.IntegerField(blank=True, help_text='Целое число, для категории - это средняя цена                                    всех дочерних товаров(включая товары подкатегорий).                                         Если цена является не целым числом, округляется                                             в меньшую сторону до целого числа. Если категория                                                не содержит товаров цена равна null.', null=True, verbose_name='Цена'),
        ),
    ]
